[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wikirefs"
version = "0.0.1"
dependencies = [
    "lxml",
    "cssselect",
    "pytest",
]

[project.scripts]

[tool.setuptools]
packages = ["wikirefs"]
